In [ ]:
import numpy as np


A = np.array([[1,2],[2,4]])

print(np.linalg.matrix_rank(A))

B = np.array([[1,2,3],[4,5,9],[5,7,12]])

print(np.linalg.det(B))

1
-2.664535259100367e-15


Exam

80 min
canvas
colba v
allowed:
open-book
open note, lab
no wamap






Topic:
1. dot prduct, projection vector
2. Linear dependent/ independent,   subspace C(A), N(A)
3. correlation, statistic(z-scores, SB, means, standaraiving data set in python), k-means
4. Linear dynmincal systems :  how to build Ax() Ax = A+z, x0;
5. Matrix properties: transpose, size of Matrix n by m (N x M)
6. Matrix algebra  multiple, add
7. Subspace: Columne space Null space. ==> systems of Equations A(x->) = (b->)
relationship is b in columne space of A;
8. properties of matrix A: det(A), inverse of A, rank of A
9. Inverse when do they exist? 
    right inverse
    *left inverse
    *full inverse
    (find using python)
10. regresion: least squeres; ^B = (X.T X)^-1 X.T
11.Regression; logistic 
GLMs

Lab 5 - 6 similar question type of qeustion

Find A
for Ax_t = x_(t+1)

find design matrix X by hand(wamap style problems)


In [ ]:
import numpy as np
# to set a vector
v1 = np.array([[2],[3]])
print(v1)
type(v1) #numpy.ndarray
#to find the size of the vector
s = v1.shape
print(s)
type(s) #type(s)

[[2]
 [3]]
(2, 1)


tuple

$||v|| = \sqrt{\Sigma_{i=1}^{n}v_i^2}  = \sqrt{v_1^2 + v_2^2 +...+ v_n^2}$

Also called the "norm" or "2-norm." If $||v|| = 1$ then we say that $v$ is a _____ vector.

<u>If $||v|| = 1$, then we say that $v$ is a unit vector</u>

In [ ]:
#this function is equal to
import numpy as np
v5 = np.array([3,4,5])
#len(v5)
v5_norm = np.linalg.norm(v5)
print(v5_norm)
#print(v5_norm)
v6 = np.array([[0],[1]])
v6_n = np.linalg.norm(v6)
print(v6_n)

#np.linalg.norm is the 

7.0710678118654755
1.0


**Exercise**. Write code using Python's built-in "sum" function to replicate np.linalg.norm(). 

In [ ]:
import math

def euclidean_norm(v):
    return math.sqrt(sum(x**2 for x in v))

v = [3, 4, 5]
norm_v = euclidean_norm(v)

print(norm_v)  # Output: 7.0710678118654755


### I. Vector Dot Product

$u \cdot v = \Sigma_{i=1}^n u_iv_i$

Other notation: $u^Tv$, $<u,v>$.

Also called the "inner" or "scalar" product.

In [ ]:
import numpy as np

u = np.array([4, -2, 3])
v = np.array([-2, 0, 1])

u_dot_v = np.dot(u, v)
print(u_dot_v)
#np.dot(u,v) is U dot V

**Angle Theorem**: $u \cdot v = cos(\theta_{u, v})||u||*||v||$

This is an expression that relates the angle between vectors $u$ and $v$ to their dot product. 

**Example**. Find the angle between u = <1, 2> and v = <3, 4> in radians and degrees.

In [ ]:
import numpy as np
import math

u = np.array([1, 2])
v = np.array([3, 4])

norm_n = np.linalg.norm(u)#magni 
norm_v = np.linalg.norm(v)

u_dot_v = np.dot(u, v)

theta_r = math.acos(u_dot_v /(norm_n * norm_v))
#this is the way to find the theta in radians

theta_d = theta_r * 180 / math.pi
#this is the way to fidn the theta in degrees


print(theta_r)
print(theta_d)

### II. Orthogonal Vector Decomposition

Also known as "orthogonal projection." Goal is to take a single vector and express it in terms of two vectors added together: one of these vectors points in a specified direction, and the other is orthogonal to this vector and is added to it to give back the original vector we started with. 

Suppose we have two non-zero vectors $v$ and $d$. Then:

\begin{align} v_{||} = proj_d v = \frac{v \cdot d}{||d||^2} d. \end{align} 

**Example**: $v = <2, 1>$, $d = <3, 1>$. Find $v_{||} = proj_d v$. What is $v_{\perp}$?

**Example**: Let A(3, -2, 5) be a point in $\mathbb{R}^3$. Let line *l* be given by $x = -2t +1$, $y = t + 2$, $z = 3t$. Find the shortest distance from *A* to *l*.  

In [ ]:
import numpy as np

v = np.array([2, 1])  # Define vector v
d = np.array([3, 1])  # Define vector d

# Calculate the dot product of v and d
v_dot_d = np.dot(v, d)

# Calculate the norm of d
norm_d = np.linalg.norm(d)

# Calculate the unit vector in the direction of d
d_unit = d / norm_d

# Calculate the projection of v onto d
v_parallel = (v_dot_d / (norm_d ** 2)) * d

# Calculate the component of v that is perpendicular to d
v_perpendicular = v - v_parallel

print(v_parallel)       # Output: [2.12132034 0.70710678]
print(v_perpendicular)  # Output: [-0.21213203  0.70710678]


To find the shortest distance from point A(3, -2, 5) to the line l: x = -2t + 1, y = t + 2, z = 3t in $\mathbb{R}^3$, we can use the formula for the distance between a point and a line in three-dimensional space. The formula is: 

In [ ]:
#d = ||A - P||

import numpy as np

A = np.array([3, -2, 5])  # Define point A
d = np.array([-2, 1, 3])  # Define direction vector of the line

# Calculate the value of t that minimizes the distance between A and the line
t = np.dot(A - np.array([1, 2, 0]), d) / np.dot(d, d)

# Calculate the closest point P on the line to A
P = np.array([1, 2, 0]) + t * d

# Calculate the shortest distance from A to the line
d = np.linalg.norm(A - P)

print(d)  # Output: 1.7320508075688772

**Exercise**. Write a function ```proj_v_d``` that returns the projection of vector ```v``` onto vector ```d```. Before you write this function be sure you understand the dimension of its inputs and outputs.

In [ ]:
import numpy as np

def proj_v_d(v, d):
    """
    Computes the projection of vector v onto vector d.
    
    Args:
    v: numpy array of shape (n,), where n is the length of the vector.
    d: numpy array of shape (n,), where n is the length of the vector.
    
    Returns:
    A numpy array of shape (n,), which is the projection of v onto d.
    """
    return np.dot(v, d) / np.dot(d, d) * d

v = np.array([1, 2, 3])
d = np.array([4, 5, 6])
proj_vd = proj_v_d(v, d)

print(proj_vd)  # Output: [1.52 1.9  2.28]


Vectors: 

v1 = <1,2>, v2 = <-3, 5>, v3 = <1, 0, 0>, v4 = <0, 1, 0>, v5 = <0, 0, 1>, v6 = <1, 1, 1>


### I. Linear Combinations of Vectors

We can build new vectors from old vectors by the vector equation:

\begin{align} \mathbb{w} = \lambda_1\mathbb{v_1} + \lambda_2\mathbb{v_2} + ... + \lambda_n\mathbb{v_p}. \end{align}

Examples: 

1. λ1 = 3, λ2 = 7. What is $\mathbb{w}$? 

2. Are v1 and v2 linearly independent? 

3. What kind of vectors can be formed from v3, v4, v5? 

4. Is {v3, v4, v5} a set of linearly independent vectors? 

5. Is {v3, v4, v5, v6} a set of linearly independent vectors? 


In [ ]:
# to find λ1 = 3, λ2 = 7. w
#w = λ1*v1 + λ2*v2


#w = 3*<1,2> + 7*<-3,5>
#  = <3,6> + <-21,35>
#  = <-18,41>


In [ ]:
import numpy as np

def is_linearly_dependent(vectors):
    """
    Checks if a set of vectors is linearly dependent.
    
    Args:
    vectors: list of numpy arrays of shape (n,), where n is the length of the vectors.
    
    Returns:
    True if the vectors are linearly dependent, False otherwise.
    """
    A = np.column_stack(vectors)
    det_A = np.linalg.det(A)
    return abs(det_A) < 1e-10  # use a tolerance for floating point comparisons


In [ ]:
v1 = np.array([[1], [2]])
v2 = np.array([[-3], [5]])
v3 = np.array([1, 0, 0])
print(is_linearly_dependent([v1, v2]))  # Output: True

v4 = np.array([0, 1, 0])
v5 = np.array([0, 0, 1])
v6 = np.array([1, 1, 1])
print(is_linearly_dependent([v3, v4, v5]))  # Output: False
#print(is_linearly_dependent([v3, v4, v5, v6]))  # Output: False

False
False


### II. Subspace and Span

Let $v_1$, ..., $v_p$ be vectors in $\mathbb{R}^n$. The set of all linear combinations of $v_1$, ..., $v_p$ is called the *span* of {$v_1$, ..., $v_p$}. If $S$ = span{$v_1$, ..., $v_p$} then we say that $S$ is the spanning set formed by the set of vectors {$v_1$, ..., $v_p$}. 


**Examples**:

1. Describe S = span{v1}.

2. Describe S = span{v1, v2}.

3. Describe S = span{v3, v4, v5}.

4. Describe S = span{v3, v4, v5, v6}.


A *subset* is a set of elements that belong to a "parent set." 
Spanning sets are commonly referred to as vector *subspaces*. More formally, a *subspace* of $\mathbb{R}^n$ is a subset $V$ such that:
1. $\vec{0} \in V$
2. $\vec{u}, \vec{v} \in V ⇒ \vec{u} + \vec{v} \in V$
3. $\vec{v} \in V ⇒ k\vec{v} \in V$.

**Examples**:

a) Is $\{<x_1, x_2>: x_1, x_2 \neq 0\}$ a subspace of $\mathbb{R}^2$?

b) Is $\{<x_1, x_2>: x_1, x_2 \geq 0\}$ a subspace of $\mathbb{R}^2$?

c) Is $\{<x_1, x_2>: x_1 x_2 \geq 0\}$ a subspace of $\mathbb{R}^2$?

d) Is $\{<x_1, x_2>: x_1 \leq x_2\}$ a subspace of $\mathbb{R}^2$?

e) Is $\{<x_1, x_2>: x_1, x_2 \in \mathbb{R}\}$ a subspace of $\mathbb{R}^2$?

f) Is $\{<x_1, x_2, 0>: x_1, x_2 \in \mathbb{R}\}$ a subspace of $\mathbb{R}^3$?

g) Is S = span{$v_3$, $v_4$} a subspace of $\mathbb{R}^3$?

h) How (if at all) are the previous three questions related? 

i) Is {$\vec{0}$} a subspace of $\mathbb{R}^n$?

j) Is $\{<x_1, x_2>: x_2 = x_1^2\}$ a subspace of $\mathbb{R}^2$?

k) Describe (in general) the 4 possible geometric shapes that form subspaces of $\mathbb{R}^3$.


In general, spanning sets create subspaces. 

Suppose that $S$ = span{$v_1$, ..., $v_p$}. Then $S$ contains all possible linear combinations of $v_1$, ..., $v_p$, where each $v_i$ is in $\mathbb{R}^n$. Check the three subspaces requirements to see that $S$ meets them, and therefore is a spanning set that creates a subspace.

**Examples**. Describe the subspace created by:

a) span{$\vec{0}$}

b) span{v3}

c) span{v3, v4}

d) span{v3, v4, v5}

e) span{v3, v4, v5, v6}


In [ ]:
import numpy as np

# define the set of vectors
v1 = np.array([1, 2, 3])
v2 = np.array([2, 5, 7])
v3 = np.array([3, 8, 11])

# stack the vectors into a matrix
A = np.column_stack([v1, v2, v3])
print(A)

# compute the reduced row echelon form of A
rref_A = np.linalg.matrix_rank(A)

# find the linearly independent vectors in the set
lin_indep_vectors = A[:, :rref_A]
print("lin_indep_vectors: " ,lin_indep_vectors)
# find all linear combinations of the linearly independent vectors
subspace = np.array([lin_indep_vectors.dot(x) for x in np.eye(rref_A)])
print("subsapce: ", subspace)

[[ 1  2  3]
 [ 2  5  8]
 [ 3  7 11]]
lin_indep_vectors:  [[1 2]
 [2 5]
 [3 7]]
subsapce:  [[1. 2. 3.]
 [2. 5. 7.]]


To find span 

In [ ]:
import numpy as np

# define the set of vectors
#v1 = np.array([1, 2, 3])
#v2 = np.array([2, 5, 7])
v1 = np.array([[1],[1],[1]])
v2 = np.array([[2],[2],[2]])
# stack the vectors into a matrix
A = np.column_stack([v1, v2])

# compute the reduced row echelon form of A
rref_A = np.linalg.matrix_rank(A)

# find the linearly independent vectors in the set
lin_indep_vectors = A[:, :rref_A]

# find all linear combinations of the vectors
span = np.array([lin_indep_vectors.dot(x) for x in np.eye(rref_A)])
print(span)


[[1. 1. 1.]]


To check basis

To check if a set of vectors forms a basis for a vector space, we need to verify two conditions:

Linear Independence: The set of vectors must be linearly independent, which means that no vector in the set can be written as a linear combination of the other vectors in the set.
Spanning: The set of vectors must span the entire vector space, which means that any vector in the space can be written as a linear combination of the vectors in the set.
To check for linear independence, we can use the determinant method or the reduced row echelon form method. We create a matrix whose columns are the vectors in the set, and then compute the determinant or reduced row echelon form of the matrix. If the determinant is non-zero or the reduced row echelon form has no zero rows, then the set is linearly independent.

To check for spanning, we can try to write any vector in the space as a linear combination of the vectors in the set. If we can find a set of coefficients that satisfy the equation, then the set spans the space.

Alternatively, we can also check if the number of vectors in the set is equal to the dimension of the vector space. If the two values are equal, then the set is a basis for the space.

In practice, we often use a combination of these methods to verify that a set of vectors forms a basis for a vector space.

In [ ]:
import numpy as np

def is_basis(A, V):
    """
    Check if the set of column vectors in A forms a basis for the vector space V.
    A: numpy array of shape (n, m), representing m column vectors in R^n
    V: numpy array of shape (n,), representing the vector space V in R^n
    Returns: True if A forms a basis for V, False otherwise.
    """
    # Check if the number of vectors in A is equal to the dimension of V
    if A.shape[1] != V.shape[0]:
        return False

    # Compute the determinant of A^T A
    ATA = np.dot(A.T, A)
    det_ATA = np.linalg.det(ATA)

    # If the determinant is nonzero, A forms a basis for V
    if abs(det_ATA) > 1e-10:
        return True

    # Otherwise, A does not form a basis for V
    return False


A = np.array([[1, 2], [3, 4]])
V = np.array([0, 0])

print(is_basis(A, V)) # False

A = np.array([[1, 0], [0, 1]])
V = np.array([0, 0])

print(is_basis(A, V)) # True


True
True


Statistic Definitions. 

### I. Statistics Definitions



*   A *population* is a complete collection of all subjects we wish to study.
*   A *sample* is a subset of the population.
*   A *variable* is a characteristic of each population member that we wish to study. In data science and machine learning a variable is often called a *feature*.
*   *Data* are measurements of a variable or variables.



a) The *mean* of a vector $x$ is defined as $\bar{x} = \frac{\Sigma_{i = 1}^nx_i}{n}$. It is a measure of center for the data vector $x$. 

b) The *standard deviation* of a vector $x$ is defined as $s_x = \sqrt{\frac{\sum_{i=1}^n (x_i - \bar{x})^2}{n}}$. It is a measure of spread for the data vector $x$.  

c) A variable that is rescaled via the equation $z_i = (x_i - \bar{x})/s_x$ is  *standardized*. $z_i$ gives the number of standard deviations that $x_i$ is above (or below) the mean. 



In [ ]:
import numpy as np
import math

x = np.array([-1, 2, 9, 20, 2, -3, -4, 9, 10, 0])

x_bar = sum(x)/len(x)
print(x_bar)
x_bar = np.mean(x)
print(x_bar)

s_x = math.sqrt(sum((x-x_bar)**2)/len(x))
print(s_x)

s_x = np.std(x)
print(s_x)

z_0 = (x[0]-x_bar)/s_x

print(z_0)


**Example**: Standardize data vector x from the previous example using ```preprocessing``` package from the ```sklearn``` library. 

In [ ]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler() #construct the scalar object
standardized_x = scaler.fit_transform(x.reshape(-1,1)) #deploy and calculate 
print(standardized_x)

### II. Correlation

The Pearson Correlation Coefficient are both measures of how closely two different data vectors correspond with each other (linear relationship). 

$r = \frac{\Sigma_{i=1}^n(x_i-\bar{x})(y_i-\bar{y})}{\sqrt{\Sigma_{i=1}^n(x_i-\bar{x})^2}\sqrt{\Sigma_{i=1}^n(y_i-\bar{y})^2}}$ 

Define the *de-meaned* (centered) vectors $\tilde{x} = x - \bar{x}$ and $\tilde{y} = x - \bar{y}$. Then 

$r = \frac{\tilde{x}\cdot\tilde{y}}{||\tilde{x}|| ||\tilde{y}||}$.

**Exercise**: Find and interpret the correlation coeffient for the following vector pairs. 

In [ ]:
import numpy as np

x1 = np.array([1, 2, 3])
y1 = np.array([2, 4, 7]) # What do you notice about these two vectors? 

cor_1 = np.corrcoef(x1, y1)
print(cor_1)

x2 = np.array([-10, 2, 9, 20, 21, -3, -4, 9, 10, 0])
y2 = np.array([-2, -13, 8, 1, 0, 0, 12, 2, 10, 1]) # I randomly chose the numbers for these vectors

cor_2 = np.corrcoef(x2, y2)
print(cor_2)

### III. K-Means Clustering

*Supervised Learning*: Algorithm is trained on labeled data, then its accuracy/effectiveness is tested by having the algorithm predict labels on other data and measuring how well it does. Example: email spam filter.

*Unsupervised Learning*: Algorithm is run (trained) on unlabled data, no way to see if it did what it was "supposed to do." Example: clustering vectors that are "similar." 

In supervised learning we define an objective function that uses the labeled outcomes in our dataset to check for algorithm convergence. Since K-Means is an unsupervised method we need to be creative in coming up with the objective function ourselves. This can be done in many different ways. The most common is using Eculidian distance to measure whether or not a particular grouping is actually "grouped." 

More formally, if $z_1, ..., z_k$ are the group centroid vectors with $j \in {1, ... , k}$, and $c_i = j$, we define the objective function as 

$J^{clust} = (||x_1 - z_{c_1}||^2 + ||x_2 - z_{c_2}||^2 + ... + ||x_n - z_{c_n}||^2)/n.$ 

We have found an "optimal" grouping when $J^{clust}$ is minimized. We can miminize $J^{clust}$ by minimizing each inidividual $||x_i - z_{c_i}||$. Thus, the optimal grouping solution is found by

$\begin{align} \underset{j = 1, 2, ..., k}{min} ||x_1 - z_j|| + \underset{j = 1, 2, ..., k}{min}||x_2 - z_j|| + ... + \underset{j = 1, 2, ..., k}{min}||x_n - z_j||.\end{align}$
 
K-Means Clustering Algorithm:

1. Choose *k*, the number of groups. Randomly initialize *k* centroids. 
2. Compute the Euclidian distance between each data observation (vector) and each of the *k* centroids. 
3. Assign each vector to the group with the closest centroid.
4. Update each centroid as the average of all vectors assigned to that centroid's group.
5. Repeat steps 2-4 until convergence.  


### see lab 2

**Exercise**. Write a function ```matrix_pow``` that returns the nth power of a given matrix. Check your work using the ```matrix_power``` module form the ```numpy.linalg``` library.

In [ ]:
import numpy as np

def matrix_pow(A,n):
  if n<1 or n%2 not in {0,1}:
    raise Exception("n is not a positive integer")
  if n == 1:
    return A
  else:
    B = A
    for i in range(0, n-1):
      B = A@B
    return B

C = 2*np.eye(3)
print(C)


# matrix * matrxi using @


**Example**. Epidemic Dynamics: simple model of disease evolution in a population. 

State vector at time $t$ is $x_t = <u_1, u_2, u_3, u_4>$, where: 

* $u_1$ is the percentage of the population that is susceptible

* $u_2$ is the percentage of the population that is infected

* $u_3$ is the percentage of the population that is recovered/immune

* $u_4$ is the percentage of the population that is deceased.

How the disease evolves from $t$ to $t+1$ (dynamics): 

* 5% of susceptible get disease, 95% remain susceptible

* of those infected: 1% die, 10% recover/immune, 4% recover/susceptible, rest remain infected.

Note: the above info is enough to infer that at any time $t$, $\sum_{i=1}^4 u_i =$__?

Model: Use above information to construct "transition" matrix $A$.

**Questions**. 
1. What percentage of the population is susceptible at $t = 20$?
2. What percentage of the population is infected at $t = 20$?
3. What percentage of the population is alive at $t = 100$?
4. What is $\lim_{t\to\infty} x_t$? Does this make sense? 
5. With some diseases, such as COVID, it is possible to lose ones' immunity. How could this be incorporated into the model? (See Lab 3!)
6. This model is very simple and completely determini


In [ ]:
#See lab 3

In [ ]:
x_0 = np.array([[1],[0], [0], [0]])


A = np.array([[.95, .04, 0, 0], [.05, .85, 0, 0], [0, .1, 1, 0], [0, .01, 0, 1]])


x_20 = matrix_pow(A,200)@x_0
print(x_20)

### I. Matrix Transpose

a) $[a_{ij}]^T = [a_{ji}]$ (Compact definition of the $A^T$)

b) $(LIVE)^T = E^TV^TI^TL^T$ (How the transpose relates to the matrix product)

c) Symmetric Matrices: $A = A^T$ (A special case) 

In [ ]:
import numpy as np

A = np.array([[2,2,3],[1,4,5],[9,3,2]])
B = np.array([[-1,-3,9],[2,-6,2],[9,8,7]])
C = np.array([[7,6],[8,-1],[9,2]])
D = np.array([[-2, 3, 1], [9, 2, 3]])
I3 = np.eye(len(A))
Ones = np.ones((3,3))
Zeros = np.zeros((3,3))
v = np.array([[1],[-2],[3]])
u = np.array([[1,-2,3]])
l = 2

**Exercise**. For any matrix $A$, what are the properties of $A^TA$? Illustrate these properties with examples in python.

In [ ]:
import numpy as np
print(A.T)

ata = A.T@A


print(ata)
print()

print(ata.T)
#simatrical

### II. Matrix Norms

Recall that the *Euclidian Norm* (2-Norm) of a vector $\vec{v}$ is $||v|| = \sqrt{\sum_{i=1}^nv_i^2}$. This is a measure of vector magnitude. 

The *Frobenius Norm* ($\ell2$ norm) of a matrix is defined as $||A||_F = \sqrt{\sum_{i=1}^N \sum_{j=1}^Ma_{ij}^2}$. 

The *trace* of a matrix is the sum of its diagonal elements: $tr(A) = \sum_{i=1}^N a_{ii}$.

Interesting property: $||A||_F = \sqrt{tr(A^TA)}$.


**Exercise**. Calculate the Frobenius norm for matrix $A$ by using a double for-loop. Verify that your function works correctly using ```norm``` from the ```numpy.linalg``` library.   

In [ ]:
import numpy as np
import math

B = np.array([[1,3,4],[2,-1,2],[4,-1,0]])
print(A[0])

def F_norm(A):
  sum = 0
  for row in A:
    for element in row:
      sum += element**2
  return math.sqrt(sum)

print(F_norm(B))
print(np.linalg.norm(B))



### column space

In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the QR decomposition of A
Q, R = np.linalg.qr(A)

# Extract the columns of Q corresponding to the pivot columns of A
pivot_cols = np.where(np.abs(np.diag(R)) > 1e-10)[0]
col_space = Q[:, pivot_cols]

print(col_space)


### null space 

In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the reduced row echelon form of A
rref_A = np.linalg.inv(A) if np.linalg.det(A) != 0 else A
rref_A = np.round(np.linalg.inv(A), 5)

# Identify the free variables in the rref of A
num_free_vars = rref_A.shape[1] - np.linalg.matrix_rank(rref_A)
free_vars = np.arange(rref_A.shape[1])[np.all(np.abs(rref_A) < 1e-10, axis=0)]
pivot_vars = np.setdiff1d(np.arange(rref_A.shape[1]), free_vars)

# Write the general solution to Ax = 0 in terms of the free variables
null_space_basis = np.zeros((rref_A.shape[1], num_free_vars))
for i, j in enumerate(free_vars):
    null_space_basis[j, i] = 1
    null_space_basis[pivot_vars] = -rref_A[:,-1][:,np.newaxis]

# The null space of A is the span of the columns of the null space basis
null_space = np.dot(null_space_basis, np.eye(num_free_vars))

print(null_space)


### I. Matrix Rank

For any matrix A:

$rank(A) =$

*   $r$ (not to be confused with the Person Correlation Coefficient!)
*   number of linearly independent columns
*   dimensionality of the column space
*   number of columns containing "information"

**Example**. Determine the rank of the following data matrix. 

In [ ]:
import numpy as np
import pandas as pd

X = np.array([[1, 1, 2], [1,0, 1], [0, 2, 2], [2, 4, 6], [3, 5, 8]])
X = pd.DataFrame(X,columns = ['Var_A','Var_B', 'Var_C'])
X.head()

a = np.linalg.matrix_rank(X)
print(a)

### II. Matrix Determinant

The matrix determinant:

a) is only defined for square matrices.

b) summarizes something like the relative size and stability of the matrix. Think of stability as sensitivity of the matrix to overflow/underflow (rounding error) when using it for computation in Python. In general, the closer to zero the determinant is, the less stable the matrix. 

c) is exactly zero if $rank(A) < M = N$. 

Thus, $det(A) = 0$ means that matrix $A$ is singular. 

In [ ]:
import numpy as np

A = np.array([[1,2],[2,4]])
B = np.array([[1,2],[2,10]])
A1 = np.array([[1,2],[2,4.0001]]) # Predict the determinant without doing this calculation! How do the stability of A and A1 compare? Demonstrate with np.linalg.solve(A,b)
C = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Hint: What is C[:,0] -2*C[:,1] + C[:,2]?


b = np.array([[1],[1]])
#x =  1* 4.001 - 2 * 2
#print(x)
#A1_rank = np.linalg.matrix_rank(A1)
#print(A1_rank)

#print(np.linalg.det(C))
#print(np.linalg.matrix_rank(C))

x = np.linalg.solve(A1,b)
print(x)

print(np.linalg.det(A1))

a1 = np.array([[1,-5],[-4,8]])
b1 = np.array([[19],[-28]])
print(np.linalg.solve(a1,b1))

### I. Matrix Inverse

A good starting place is to think about solution(s) to $Ax = b$. 

To solve this equation you have 3 options:

1. Solve an equation for a variable, then backsolve (high school algebra).  
2. Set up an augmented matrix $[A | b]$ and perform elementary row operations.
3. Find the matrix inverse $A^{-1}$ and express $x$ as the matrix-vector product $A^{-1}b$. 

#### Conditions for a matrix $A$ to have a full-inverse $A^{-1}$:

A <u>full-inverse</u> of $A$ is a matrix $A^{-1}$ such that $AA^{-1} = I$ and $A^{-1}A = I$. 
//only square matrix
1. $A$ must have $M = N$. 
2. $A$ must be "full-rank", ie, $r = M = N$. 

**Exercises**. For each of the following system of equations, put the system into $Ax = b$ form. Then find:

a) $C(A)$ //column space of A 


b) $N(A)$ // null space of A 

c) $rank(A)$ //rank of A 

d) $det(A)$ //determeint of A 

e) the solution $\vec{x}$

* $2x_1 + x_2 = 3$, $x_1 + 2x_2 = 3$
* $2x_1 + x_2 = 3$, $-4x_1 - 8x_2 = -12$
* $2x_1 + x_2 = 3$, $-4x_1 - 8x_2 = -8$

In [ ]:
import numpy as np

A = np.array([[2,1],[1, 2]])
b = np.array([[3],[3]])

A1 = np.array([[4,2],[-2, -1]])
b1 = np.array([[6],[-3]])

A_inv = np.linalg.inv(A)
print(A_inv)

A_inv@b

#### II. One-Sided Inverses

A <u>left-inverse</u> is a matrix $L$ such that $LA = I$. 

A <u>right-inverse</u> is a matrix $R$ such that $AR = I$. 



Here is some sample Python code to find the left inverse of a matrix A using the numpy library:

In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[1, 2, 3], [4, 5, 6]])

# Check if A has a left inverse
if np.linalg.matrix_rank(A) == A.shape[1]:
    # Compute the left inverse of A
    left_inv_A = np.linalg.inv(A.T @ A) @ A.T
    print("Left inverse of A:")
    print(left_inv_A)
else:
    print("A does not have a left inverse.")


How about right inverse? 

In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[1, 2], [3, 4], [5, 6]])

# Check if A has a right inverse
if np.linalg.matrix_rank(A) == A.shape[0]:
    # Compute the right inverse of A
    right_inv_A = np.linalg.inv(A @ A.T) @ A
    print("Right inverse of A:")
    print(right_inv_A)
else:
    print("A does not have a right inverse.")


**Example**. Find a left-inverse matrix $L$ for $A$ = [[-1, 0], [0, 4], [1, 0]]. 

**Question**. Is $L$ unique? 

In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[-1, 0], [0, 4], [1, 0]])

# Check if A has a left inverse
if np.linalg.matrix_rank(A) == A.shape[1]:
    # Compute the left inverse of A
    left_inv_A = np.linalg.inv(A.T @ A) @ A.T
    print("Left inverse of A:")
    print(left_inv_A)
else:
    print("A does not have a left inverse.")


Left inverse of A:
[[-0.5   0.    0.5 ]
 [ 0.    0.25  0.  ]]


1. Given the points A: (3,4,6) and B: (6,3,-5), find the vector $\vec{u}$ = $\vec{AB}$.


### Answer

B - A 



 


2. Let $\vec{a}$ = <5, -5, 2>, find |$\vec{a}$|= $\sqrt{\sum_{i=1}^nv_i^2}$


The distance between the points  P(3,4,3)andQ(1,0,-3)  is:$\sqrt{\sum_{i=1}^n(Q-P)^2}$





Find a vector $\vec{v}$ parallel to $\vec{u}$ = -4$\vec{i}$+5$\vec{j}$-2$\vec{k}$ and with magnitude ||$\vec{v}$|| = 3.

$\vec{v}$ = -12/$\sqrt(45)$ i + 15/$\sqrt(45)$j-6/sqrt(45)k

all number * 3 and 
4^2 + 5^2 + 2^2 srqt;




To find a matrix is what by whay, we first look at the row then column. 

Matrix A has the dimensions 4 X 6 and Matrix B has the dimensions 6 X 3 

What are the dimensions of the product  ?


4 X 3

In [ ]:
import numpy
D = numpy.array([[0,-5,3],[8,9,10],[-2,-8,5]])

D_T = D + D.T

print(D_T)


[[ 0  3  1]
 [ 3 18  2]
 [ 1  2 10]]


In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[1, -2], [-2,4], [-1,3]])

# Compute the reduced row echelon form of A
rref_A = np.linalg.inv(A) if np.linalg.det(A) != 0 else A
rref_A = np.round(np.linalg.inv(A), 5)

# Identify the free variables in the rref of A
num_free_vars = rref_A.shape[1] - np.linalg.matrix_rank(rref_A)
free_vars = np.arange(rref_A.shape[1])[np.all(np.abs(rref_A) < 1e-10, axis=0)]
pivot_vars = np.setdiff1d(np.arange(rref_A.shape[1]), free_vars)

# Write the general solution to Ax = 0 in terms of the free variables
null_space_basis = np.zeros((rref_A.shape[1], num_free_vars))
for i, j in enumerate(free_vars):
    null_space_basis[j, i] = 1
    null_space_basis[pivot_vars] = -rref_A[:,-1][:,np.newaxis]

# The null space of A is the span of the columns of the null space basis
null_space = np.dot(null_space_basis, np.eye(num_free_vars))

print(null_space)


LinAlgError: ignored

In [ ]:
import numpy as np

A = np.array([[1,-5],[-4,8]])

print(np.linalg.inv(A))

[[-0.66666667 -0.41666667]
 [-0.33333333 -0.08333333]]


The table below show data that has been collected from different fields from various farms in a certain valley. The table contains the grams of Raspberries tested and the amount of their Vitamin C content in mg. Find a linear model that express Vitamin C content as a function of the weight of the Raspberries.


Y = a + bX

b =(nsum(xy)-sum(x)*sum(Y))/(n*sum(x^2)-sum(x)^2)

a=(sum(y)-(b*sum(X))) / n

In [ ]:
import numpy as np
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
B = A.T
print(B)
print(np.linalg.matrix_rank(A@B))

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
2


In [ ]:
import numpy as np

V = np.array([[1,2],[3,7]])
print(V)
print(np.linalg.det(V@V.T))

[[1 2]
 [3 7]]
0.9999999999999964


In [ ]:
import numpy as np

# Define the logistic regression equation
def logistic_regression(beta_0, beta_1, beta_2, beta_3, x1, x2, x3):
    log_odds = beta_0 + beta_1*x1 + beta_2*x2 + beta_3*x3
    probability = np.exp(log_odds) / (1 + np.exp(log_odds))
    return probability

# Set the values of beta and the predictor variables
beta_0_hat = 0.2
beta_1_hat = -0.3
beta_2 = 9
beta_3 = 0.5
x1 = 100
x2 = 3
x3 = 2

# Calculate the predicted probability using the logistic regression equation
predicted_prob = logistic_regression(beta_0_hat, beta_1_hat, beta_2, beta_3, x1, x2, x3)
print("The predicted probability of voting 'yes' is:", predicted_prob)

The predicted probability of voting 'yes' is: 0.1418510649004877


In [ ]:
import numpy as np
import math



def matrix_pow(a, n):
  if n < 1 or n%2 not in {0, 1}:
    raise Exception("n is not a positive interger")
  else:
    ans = a
    for i in range(0,n):
     ans *= a
  return ans

def markov(A, n, x_0):
  x_n = matrix_pow(A,n)@x_0
  return x_n

import numpy as np
x_0 = np.array([[0],[30],[5]])
A = np.array([[0, 0.1, 0.25],[0.1, 0, 0.15],[0, 0, 0.85]])
print(markov(A, 10, x_0))

[[0.00000000e+00]
 [0.00000000e+00]
 [2.65429956e-72]]


In [ ]:
[[0.   0.1  0.25 ]
 [0.1  0.   0.15 ]
 [0.   0.   0.85 ]]

Suppose an investor put 30% of their money in stock A for one year, and the rest in stock B. Stock A had a return of 10%, whereas stock B lost 2%. The 1-year treasury bill rate at the time of the investment was 6%. The standard deviation of the returns on both stocks was 10 and the two stocks had a correlation of p = 0.


The table below show data that has been collected from different fields from various farms in a certain valley. The table contains the grams of Raspberries tested and the amount of their Vitamin C content in mg. Find a linear model that express Vitamin C content as a function of the weight of the Raspberries.


Y = a + bX

b =(nsum(xy)-sum(x)*sum(Y))/(n*sum(x^2)-sum(x)^2)

a=(sum(y)-(b*sum(X))) / n

In [ ]:
#sum(xy)
a = 1 *1 + 2*1 + 3*2 + 4* 4 + 6 * 5 + 7 * 7
print("a", a)
#sum(x) 6
b = 1 + 2 + 3 + 4 + 6 + 7
print("b", b)
c = 1**2 + 2**2 + 3**2 + 4**2 + 6**2 +7**2
print("c", c)
d = b**2
print("d", d)
#sum y
e = 1 + 1 + 2 + 4 + 5 + 7
print("e", e)

m = (6 * a - b * e)/(6 * c - d)
print(m)

g = (e-(6*a))/6
print(g)

a 104
b 23
c 115
d 529
e 20
1.0186335403726707
-100.66666666666667
