## Lab 1: Vectors in Python

The purpose of this lab is to get more practice constructing and maniuplating vectors in Python. Much of this material is similar to what we have done in class. If you are struggling with this lab review Chapter 16 as needed; reach out to your instructor (early) if necessary. 


### I. Vectors in Python

In [ ]:
import numpy as np

w = np.array([[4],[0], [9], [-9], [8], [-2], [19], [2], [1]])
v = np.array([-2, 3, 7])
u = np.array([-1, -4, 5])



9


**Exercise 1**. Suppose you want to access the element valued 19 from w. To do so you should type the code w[a][b], with a = __ and b = __.

In [ ]:
w[6][0]
#print(w[6][0])

19


**Exercise 2**. Find 3u - 7v. Its third element is the number __. 

In [ ]:
x1 = 3 * u - 7 * v
#print(x1)
x1[2]

[ 11 -33 -34]


-34

**Exercise 3**. Find $v \cdot u$. 

In [ ]:

x2 = np.dot(v, u)
#x3 = np.dot(u,v)
#print(x2)
#print(x2)

25


**Exercise 4**. Find $v_{||} = proj_{u} v$. Its third element is __. 

Hint: Use a function we wrote in class. 


In [53]:
def proj_v_d(v,d):
  result = (np.dot(v,d)/(np.linalg.norm(d)**2))*d
  return result 


v_parralel = proj_v_d(v,u)
print(v_parralel)

[-0.5952381  -2.38095238  2.97619048]


**Exercise 5**. Find $v_{\perp}$ using your result from the previous exercise. Its third element is __. If you did these exercises correctly you should find that $v_{||} \cdot v_{\perp} =$ __. 

In [55]:
v_perp = v - v_parralel
print(v_perp)

v_parralel_dot_v_perp = np.dot(v_parralel, v_perp)
print(v_parralel_dot_v_perp)

[-1.4047619   5.38095238  4.02380952]
0.0


**Exercise 6**. The root-mean-square (rms) of a vector **x** is defined as $\sqrt{\frac{\sum_{i=1}^n x_i^2}{n}}$. The rms and its variations are commonly used to measure the accuracy of a machine learning algorithm's performance (we'll study this in detail in week 9). 

Write a python function called ```rms``` that takes a vector **x** as an input and returns its root-mean-square. 

rms(w) = __. 

In [36]:
import math
def rms(x):
  sum_of_x = np.linalg.norm(x)
  x_size = x.size
  res = sum_of_x / math.sqrt(x_size)


  return res

  rms_w = rms(w)
  print(rms_w)

  


**Exercise 7**. The ```rms``` function you wrote in the previous exercise applied to vector **w** is $rms:\mathbb{R}^a ⟶ \mathbb{R}^b$. 

a = _ and b = _. 

In [37]:
res7 = rms(w)
print(res7)


8.246211251235321


**Exercise 8**. Write a function called ```dist``` that takes vectors **a** and **b** as inputs and returns the distance between the tips of **a** and **b**. Assume that any two input vectors are of the same dimension. 

dist(u,v) = __. 

In [51]:
import math
import numpy as np

def dist(b, a):
  ans = np.linalg.norm(a - b)

  return ans
 
  v = np.array([-2, 3, 7])
  u = np.array([-1, -4, 5])



In [52]:
print(dist(u,v))

7.3484692283495345


### II. Python Control Flow

Read pages 297-300 in *Practical Linear Algebra*. If you have seen "if" statements and "for loops" before this material will be very easy for you; if not be sure to carefully review the assigned reading and spend some time playing with these examples. We will see Control Flow in class next week. 

**Example 1**. Consider the following for-loop:

In [ ]:
n = 10
for i in range(n):
  print(i)

print("Done.")

0
1
2
3
4
5
6
7
8
9
Done.


```range(n)``` is an iterable generator function, it produces the "next" number in a sequence on demand. The first thing that happens in the above code block is that we assign the integer 10 to the variable name "n". Then the for-loop runs: *i* is a placeholder variable that changes (increments by +1) every time we go through the loop. The first value that range(10) produces is 0 (by default). Then print(0) happens, then control is returned to the top of the loop. range(10) produces 1, which is then passed to the body of the loop and print(1) happens, and so on. The 10th value produced by range(10) is the last value that is run, which is 9; print(9) happens, then control is passed to the next line after the for-loop, which is print("Done.")


**Exercise 9**. Write a for loop that prints numbers 0, 1, 8, 27, 64. 

In [ ]:
n = 65

for i in range(n):
  if i in{0, 1, 8, 27, 64}:
    print(f"{i}")

0
1
8
27
64


**Example 2**. Consider the following for-loop:

In [ ]:
n = 6

for i in range(n):
  if i in {0, 1, 3, 5, 8, 13}:
    print(f"i = {i} is in the set!")
  else:
    print(f"i = {i} is not in the set.")

i = 0 is in the set!
i = 1 is in the set!
i = 2 is not in the set.
i = 3 is in the set!
i = 4 is not in the set.
i = 5 is in the set!
i = 6 is not in the set.
i = 7 is not in the set.
i = 8 is in the set!
i = 9 is not in the set.
i = 10 is not in the set.
i = 11 is not in the set.
i = 12 is not in the set.


**Exercise 10**. If you want the loop to print "i = 13 is in the set!" you need to set ```n``` to at least __. 

you must set n as i + 1
