## Lab 3: Linear Dynamical Systems
The purpose of this lab is to utilize the computing power of the python environment to find future-state vectors of linear dynamical systems (Markov Processes). The following model is adapted from *Introduction to Applied Linear Algebra* by Boyd and Vandenberghe (2018).

**Exercise 1**. Write a function called ```markov``` that takes the transition matrix ```A```, a time ```n``` and an initial vector ```x_0``` as inputs and returns ```x_n```. (Using this function will save you some time on the following exercises.)

In [ ]:
import numpy as np
import math

def matrix_pow(A,n):
  if n<1 or n%2 not in {0,1}:
    raise Exception("n is not a positive integer")
  if n == 1:
    return A
  else:
    B = A
    for i in range(0, n-1):
      B = A@B
    return B

def markov(A, n, x_0):
  x_n = matrix_pow(A,n)@x_0
  return x_n




### I. Linear Dynamical Systems in Pharmaco-Kinetics

A *compartmental system* is a model used to describe the movement of some material over time among a set of *n* compartments of a system, and the outside world. It is widely used in *pharmaco-kinetics*, the study of how the concentration of a drug varies over time in the body. In this application, the material is a drug, and the compartments are the bloodstream, lungs, heart, liver, kidneys, and so on. Compartmental systems are special cases of linear dynamical systems.

In the following exercises we will consider a very simple compartmental system with 3 compartments. We let $x_t$ denote the amount of material (drug) in the system at time period $t$. Between period $t$ and $t+1$, the material moves as follows.



* 10% of the material in compartment 1 moves to compartment 2. (This decreases the amount in compartment 1 and increases the amount in compartment 2.)
* 5% of the material in compartment 2 moves to compartment 3.
* 5% of the material in compartment 3 moves to compartment 1.
* 5% of the material in compartment 3 is eliminated.

Express this compartmental system as a linear dynamical system, $x_{t+1} = Ax_t$.



**Exercise 2**. Suppose that each “compartment” is an organ in the human body, vector $x_t$ represents the amount (in milligrams) of a certain medication in each organ at time t (in hours), and the “body” represents all 3 organs. Suppose that 10 milligrams of the medication is injected directly into Organ 1 at $t = 0$. This would imply that the initial vector $x_0$ is <__, __, __>.

In [ ]:
#x0 = <10, 0,0>

**Exercise 3**. Find matrix $A$. Check that your $A$ matrix and initial vector $x_0$ are correct by verifying that $x_3$ = <7.2925, 2.5675, 0.1375>. Then find $x_{100}$.

In [ ]:
x_0 = np.array([[10],[0],[0]])

A = np.array([[0.9,0,0.05],[0.1,0.95,0],[0,0.05,0.9]])

A = np.array([[ 0.75,0.1, ],[ 0,0.8, 0],[ 0.25, 0.1,0.75 ]])
print(markov(A, 100, x_0))
#0.8244

[[0.48624228]
 [1.3978752 ]
 [0.82442603]]


**Exercise 4**. What build-in python function can you use on $x_t$ to return the total amount of the medication in the body at time $t$? Use this function to find the total amount of medication in the body at $t = 2$. Explain (in a sentence) why this answer makes sense.

In [ ]:
print(markov(A,2,x_0))

x_2 = matrix_pow(A, 2)
print()
print(x_2)
#using matrix_pow(A, 2) which will give you [[0.81, 0.0025, 0.09],[[0.185, 0.9025, 0.005], [0.005, 0.0925, 0.81]]] which is same as markov(A,2,x_0) provide ([[8.1],[1.85],[0.05]]), The markov funciotn only sepreat the first column and by time 10 to that column.


[[8.1 ]
 [1.85]
 [0.05]]

[[0.81   0.0025 0.09  ]
 [0.185  0.9025 0.005 ]
 [0.005  0.0925 0.81  ]]


**Exercise 5**. Find the “half-life” of this medication by finding the (approximate) value of $t$ at which time half of the initial dose remains in the body. (Hint: this will take some trial-and-error.)

In [ ]:
x_half = pow(0.5, 10)
print(x_half)

x_0 = np.array([[10],[0],[0]])

A = np.array([[0.9,0,0.05],[0.1,0.95,0],[0,0.05,0.9]])

print(markov(A, 60, x_0))
#60

8.673617379884035e-19
[[0.89366172]
 [2.58398365]
 [1.52635179]]


**Exercise 6**. Approximately how many hours does it take for there to be 3 milligrams of the medication left in Organ 1?

In [ ]:
x_0 = np.array([[3],[0],[0]])

A = np.array([[0.9,0,0.05],[0.1,0.95,0],[0,0.05,0.9]])

print(markov(A, 100000, x_0))
#12

[[3.705e-322]
 [1.023e-321]
 [5.188e-322]]


**Exercise 7**. According to this model, will there ever be exactly 0 milligrams of medication left in the body? What is the intuition behind this? Is this aspect of the model realistic?  

In [ ]:
#There will never be exactly 0 millgrams of medication left in the body, only approximate 0. a number to the Nth power will never be 0. This is aspect of the model is not realistic, it is idealism.

**Exercise 8**. Suppose that at $t = 50$ another 5 milligrams is injected into Organ 1. How much medication is left in the body at $t = 100$? (Hint: think about how this changes $x_{50}$ and how many more hours it will take to get to 100.)

In [ ]:
#t = 50
x_0 = np.array([[10],[0],[0]])

A = np.array([[0.9,0,0.05],[0.1,0.95,0],[0,0.05,0.9]])

print(markov(A, 50, x_0))
x_50 = np.array([[6.03026362],[3.026031],[1.77907303]])
print()
print(markov(A, 100, x_50))

print()
print(markov(A,100, x_0))


[[1.03026362]
 [3.026031  ]
 [1.77907303]]

[[0.46896425]
 [1.34826611]
 [0.79515736]]

[[0.48624228]
 [1.3978752 ]
 [0.82442603]]


### II. Epidemic Dynamics Model Revisited

Consider the epidemic dynamics model discussed in class. Suppose that the diease evolves as described in the lecture notes, but now it is possible for the "recovered/immune" group to lose their immunity. Suppose that at every transition from $t$ to $t+1$ 3% of the recovered/immune group lose their immunity and become susceptible.

**Exercise 9.** What percentage of the population is in the "susceptible" group at $t=100$ (for the updated model)?

In [ ]:
x_0 = np.array([[10],[0],[0]])

A = np.array([[0.9,0.03,0.05],[0.1,0.95,0],[0,0.05,0.9]])

x_100 = (matrix_pow(A,100)@x_0)
print(x_100)


[[3.90549366]
 [7.39357229]
 [3.59531979]]


**Exercise 10**. Compare the $x_{100}$ vector for this updated model with the $x_{100}$ vector from the original model. Explain (in a few sentences) why these vectors are different. Which model would be better for predicting the dynamics of virus like COVID?

In [ ]:
x_0 = np.array([[10],[0],[0]])

A = np.array([[0.9,0,0.05],[0.1,0.95,0],[0,0.05,0.9]])

print(markov(A, 100, x_0))
print()


x_1 = np.array([[10],[0],[0]])

A1 = np.array([[0.9,0,0.05],[0.1,0.95,0],[0,0.05,0.9]])

x_101 = (matrix_pow(A1,100)@x_1)
x_101 = markov(A1, 100, x_1)
print(x_101)

[[0.48624228]
 [1.3978752 ]
 [0.82442603]]

[[3.18252377]
 [6.22574209]
 [4.02264046]]
