Reading: Chapter 16 pages 279 - 285, "Print Formatting and F-Strings" pages 296-297; Chapter 2 pages 7-18;

Lecture Topics:

1.   Vectors in $\mathbb{R}^n$
2.   Vectors in Python
3.   Vector operations



### I. Vectors

  \begin{align}
    \mathbb{x} &= \begin{bmatrix}
           x_{1} \\
           x_{2} \\
           \vdots \\
           x_{n}
         \end{bmatrix}
  \end{align}

is a general column vector in $\mathbb{R}^n$.

Specific vectors are:

a) v1 = $[1, -8]$  <u>//**this a row vector and $\mathbb{R}^2$.</u>

b) v2 = $<1, -8>$ <u>//** is the same vector as V1 but it is the column vector</u>

c) v3 = $[1, -8]^T$ <u>//**T measn Transpose; it chagnes the row vector to column vector</u>

d) v4 = $[-9, 2, 4, 9, 2, 0, 0, 1000000, 0.1]$ <u>//** is a row vector in $\mathbb{R}^9$.</u>

e) $\vec{c} = <0, 0, 0, 0>$ <u>//** it is column vector in $\mathbb{R}^4$. </u>

f) $\vec{d} = \vec{1}$

The above vectors are in _______ dimensions.
Unless otherwise specified we generally assume that $v$ is a _____ (row, column) vector.

Geometrically a vector can be placed anywhere in space, but a vector in $\mathbb{R}^n$ is in *standard position* if its tail is placed at the _____.

### II. Vectors in Python: construction, methods, indexing, numpy

**Examples**.

In [ ]:
v1 = [1, -2, 3]
# type()
# len()
# v1[0]
# a = [v1[0], v1[1], v1[-1]]


In [ ]:
z = [[-1,2,3], [8, 9, 10]]
z[0]
z[0][1]
z[1][2]

10

In [ ]:
import numpy as np

v2 = np.array([1, -2, 3])

v2.shape

v3 = np.array([[1, -2, 3]])
print(v3)
v3.shape #shape (1,3) means 1 row and 3 column

v4 = np.array([[1], [-2], [3]])

v4.shape #shape (3, 1) means 3 row and 1 column

[[ 1 -2  3]]


(3, 1)

**Exercise**. Use numpy to construct a ones row vector called ```ones``` in $\mathbb{R}^9$.

In [ ]:
import numpy as np
#ones = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1])
v7 = np.ones((1,8))
print(v7)


[[1. 1. 1. 1. 1. 1. 1. 1.]]


**Exercise**. Use the numpy package to construct a 3 by 3 matrix ```m1``` with ones on the diagonal, zeros everywhere else.

In [ ]:
import numpy as np

#m1 = np.array([[0, 0, 0],[0, 0, 0],[0, 0, 0]])
#m1 = np.zeros([3,3])
m1 = np.eye(3)
print(m1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#v1 = np.array([1,2])
#v2 = np.array([[1,2]]) row vector
#v3 = np.array([[1],[2]]) column vector

### III. Operations on Vectors: Addition, Multiplication, Transpose

In [ ]:
v1 = np.array([[1],[2],[3]])
v2 = np.array([[-1],[-2],[-3]])
v3 = np.array([[4],[5],[6]])

print(v1 - v2)


[[2]
 [4]
 [6]]


### IV. Vector Magnitude

$||v|| = \sqrt{\Sigma_{i=1}^{n}v_i^2}  = \sqrt{v_1^2 + v_2^2 +...+ v_n^2}$

Also called the "norm" or "2-norm." If $||v|| = 1$ then we say that $v$ is a _____ vector.

In [ ]:
import numpy as np

v5 = np.array([3,4,5])
#len(v5)
v5_norm = np.linalg.norm(v5)
#print(v5_norm)
v6 = np.array([[0],[1]])
v6_n = np.linalg.norm(v6)

**Exercise**. Construct a vector ```v7``` that points in the opposite direction as v5 but is twice its length.

In [ ]:
v7 = 2 * -np.array([3, 4, 5])
v7 = 2 * -v5
print(v7)

[ -6  -8 -10]


**Exercise**. Construct a vector ```v8``` that points in the same direction as v5 but has unit length.



In [ ]:
import numpy as np

v5 = np.array([3, 4, 5])
v8 = v5 / np.linalg.norm(v5)
v8_n = np.linalg.norm(v8)
print(v8)  # Output: [0.42426407 0.56568542 0.70710678]
print(v8_n)

[0.42426407 0.56568542 0.70710678]
0.9999999999999999


**Exercise**. Write code using Python's built-in "sum" function to replicate np.linalg.norm().

In [ ]:
import math

def euclidean_norm(v):
    return math.sqrt(sum(x**2 for x in v))

v = [3, 4, 5]
norm_v = euclidean_norm(v)

print(norm_v)  # Output: 7.0710678118654755

**Exercise**. What is the distance between the tips of <3, 5> and <2, 3>?


In [ ]:
import numpy as np

# Define the vectors as NumPy arrays
v1 = np.array([3, 5])
v2 = np.array([2, 3])

# Calculate the distance using NumPy functions
distance = np.linalg.norm(v2 - v1)

print(distance)  # Output: 2.23606797749979

**Exercise**. Find a vector z with ||z|| = 4 pointing opposite of v = -i + 2j + 4k.




To find a vector z with norm ||z|| = 4 pointing opposite of vector v = -i + 2j + 4k, we can negate the direction of v by multiplying it by -1, then normalize it by dividing it by its norm, and finally scale it by multiplying it by 4. Here's the process in steps:

Negate the direction of v: -v = i - 2j - 4k
Normalize -v to obtain a unit vector: -v/||v|| = (i - 2j - 4k)/sqrt(1^2 + (-2)^2 + (-4)^2) = (i - 2j - 4k)/sqrt(21)
Scale the unit vector by multiplying it by 4: z = 4*(-v/||v||) = -4*(i - 2j - 4k)/sqrt(21)
Therefore, the vector z with ||z|| = 4 pointing opposite of v = -i + 2j + 4k is -4*(i - 2j - 4k)/sqrt(21).

We can use Python to calculate z as follows:

In [ ]:
import numpy as np

v = np.array([-1, 2, 4])  # Define vector v
z = -4*v/np.linalg.norm(v)  # Calculate vector z

print(z)  # Output: [ 1.50755672 -3.01511344 -6.03022688]

[ 0.87287156 -1.74574312 -3.49148624]
