Reading: Pages 129-138.

### I. Matrix Inverse

A good starting place is to think about solution(s) to $Ax = b$.

To solve this equation you have 3 options:

1. Solve an equation for a variable, then backsolve (high school algebra).  
2. Set up an augmented matrix $[A | b]$ and perform elementary row operations.
3. Find the matrix inverse $A^{-1}$ and express $x$ as the matrix-vector product $A^{-1}b$.

#### Conditions for a matrix $A$ to have a full-inverse $A^{-1}$:

A <u>full-inverse</u> of $A$ is a matrix $A^{-1}$ such that $AA^{-1} = I$ and $A^{-1}A = I$.
//only square matrix
1. $A$ must have $M = N$.
2. $A$ must be "full-rank", ie, $r = M = N$.

**Exercises**. For each of the following system of equations, put the system into $Ax = b$ form. Then find:

a) $C(A)$ //column space of A


b) $N(A)$ // null space of A

c) $rank(A)$ //rank of A

d) $det(A)$ //determeint of A

e) the solution $\vec{x}$

* $2x_1 + x_2 = 3$, $x_1 + 2x_2 = 3$
* $2x_1 + x_2 = 3$, $-4x_1 - 8x_2 = -12$
* $2x_1 + x_2 = 3$, $-4x_1 - 8x_2 = -8$

**Exercise**. Find inverses for the following matrices in Python.

In [ ]:
import numpy as np

#A = np.array([[4,2],[2, -8]])
#b = np.array([[6],[12]])

A1 = np.array([[4,2],[-2, -1]])
b1 = np.array([[6],[-3]])


A = np.array([[2,1],[1, 2]])
b = np.array([[3],[3]])



A_inv = np.linalg.inv(A)
print(A_inv)


print(A_inv@A)

print(A@A_inv) #indentitiy


print(A_inv@b)
#X = np.array([[2,1],[-4,-8]])
#print(X)
#print(np.linalg.matrix_rank(X))
#print(np.linalg.det(X))

#A1 = np.array([[19,12],[11,7]])
#print(A1.T)

[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1.]
 [1.]]


#### II. One-Sided Inverses

A <u>left-inverse</u> is a matrix $L$ such that $LA = I$.

A <u>right-inverse</u> is a matrix $R$ such that $AR = I$.




**Example**. Find a left-inverse matrix $L$ for $A$ = [[-1, 0], [0, 4], [1, 0]].

**Question**. Is $L$ unique?

**Theorem**. Suppose that a matrix $A$ has $M > N = r$. Then $A^TA$ also has rank $N = r$.

**Example**. Find a left-inverse for a matrix $A$ that has $M > N = r$.