Reading: Chapter 16 pages 285 - 288; Chapter 2 pages 18-29;

Lecture Topics:

1. Vector Products
2. Vector Orthogonal Decomposition
3. Vector Functions



### I. Vector Dot Product


$u \cdot v = \Sigma_{i=1}^n u_iv_i$

Other notation: $u^Tv$, $<u,v>$.

Also called the "inner" or "scalar" product.

**Exercise**: Find the dot product of $4i - 2j + 3k$ and $-2i + k$. u dot v = 4 * (-2) + (-2) * 0 + 3 * 1

**Exercise**: Express $||v||$ in terms of the dot product.  v dot v

**Exercise**: Suppose that $a$ is a general vector in $\mathbb{R}^n$. Use the dot product to write an expression that represents the sum of all the elements of $a$. 

**Exercise**. Compute the inner product of <4, -2, 3> and <-2, 0, 1>.

In [ ]:
import numpy as np

u = np.array([4, -2, 3])
v = np.array([-2, 0, 1])

u_dot_v = np.dot(u, v)
print(u_dot_v)


-5


### II. Angle and Dot Product


**Angle Theorem**: $u \cdot v = cos(\theta_{u, v})||u||*||v||$

This is an expression that relates the angle between vectors $u$ and $v$ to their dot product. 

**Example**. Find the angle between u = <1, 2> and v = <3, 4> in radians and degrees.


In [ ]:
import numpy as np
import math

u = np.array([1, 2])
v = np.array([3, 4])

norm_n = np.linalg.norm(u)#magni 
norm_v = np.linalg.norm(v)

u_dot_v = np.dot(u, v)

theta_r = math.acos(u_dot_v /(norm_n * norm_v))

theta_d = theta_r * 180 / math.pi


print(theta_r)
print(theta_d)

0.17985349979247847
10.304846468766044


In [ ]:
import numpy as np
import math




6

2
[-2 10 14]


**Exercise**: Use the Angle Theorem to show that the dot product of *any* two orthogonal vectors is 0.

**Exercise**: Use the Angle Theorem to show that if the dot product of any two vectors is 0 then the angle between them is 90 degrees. 

In [ ]:
#u·v = ||u|| ||v|| cos(θ)
import numpy as np

# Define two orthogonal vectors
u = np.array([1, 0])
v = np.array([0, 1])

# Calculate their dot product
u_dot_v = np.dot(u, v)

print(u_dot_v)  # Output: 0


In [ ]:
import numpy as np

# Define two vectors with dot product 0
u = np.array([1, 0])
v = np.array([0, 1])

# Calculate their dot product
u_dot_v = np.dot(u, v)

# Calculate the angle between them using the Angle Theorem
theta_r = np.arccos(u_dot_v / (np.linalg.norm(u) * np.linalg.norm(v)))
theta_d = theta_r * 180 / np.pi

print(theta_d)  # Output: 90.0

### II. Orthogonal Vector Decomposition


Also known as "orthogonal projection." Goal is to take a single vector and express it in terms of two vectors added together: one of these vectors points in a specified direction, and the other is orthogonal to this vector and is added to it to give back the original vector we started with. 

Suppose we have two non-zero vectors $v$ and $d$. Then:

\begin{align} v_{||} = proj_d v = \frac{v \cdot d}{||d||^2} d. \end{align} 

**Example**: $v = <2, 1>$, $d = <3, 1>$. Find $v_{||} = proj_d v$. What is $v_{\perp}$?

**Example**: Let A(3, -2, 5) be a point in $\mathbb{R}^3$. Let line *l* be given by $x = -2t +1$, $y = t + 2$, $z = 3t$. Find the shortest distance from *A* to *l*.  



In [ ]:
import numpy as np
v = ([2, 1])
d = ([3, 1])

v_dot_d = np.dot(v, d)
norm_d = np.linalg.norm(d)

v_p = v_dot_d / (norm_d * norm_d) 

print(v_dot_d)
print(norm_d)

7
3.1622776601683795


### III. Functions


Function analysis isn't the focus of linear algebra (as compared to say, calculus) but functions are always there in the background. For example


*   The magnitude of a vector is a function $f:\mathbb{R}^n ⟶ \mathbb{R}$
*   The dot product can be interpreted as $f: \mathbb{R}^n × \mathbb{R}^n ⟶ \mathbb{R}$.  
*   The parametric curve (line) *l* in the previous example can be interpreted as $f: \mathbb{R}^? ⟶ \mathbb{R}^?$. 

The most common place that functions show up (directly) in this course is in Python. We have already used quite a few built-in functions (name a few). Python has special syntax (*def*, *return*, and indentation) for writing new functions. 

    *def* function_name(input1, input2,...): 

        Body of function that does the computing work goes here.

        *return* outputs

**Exercise**. Write a funion called ```vec_sq``` that takes a vector ```w``` as an input and returns a vector with ```w```'s elements squared. 

In [ ]:
import numpy as np

def vec_sq(w):
    """
    Computes a vector with the squared elements of input vector w.
    
    Args:
    w: numpy array of shape (n,), where n is the length of the vector.
    
    Returns:
    A numpy array of shape (n,), where each element is the square of the corresponding
    element in w.
    """
    return np.square(w)

array([3, 0])

**Exercise**. Write a function ```proj_v_d``` that returns the projection of vector ```v``` onto vector ```d```. Before you write this function be sure you understand the dimension of its inputs and outputs.

In [1]:
def proj_v_d(v, d):
  d_norm = np.sqrt(sum(v**2))
  
  res = (np.dot(v, d)/d_norm**2)*v
  return res


In [ ]:
from numpy.core.fromnumeric import reshape
import numpy as np
import math

u = np.array([2, -7, -5])
v = np.array([0, 0.6, 0.8])

res = (np.dot(u,v)/np.linalg.norm(v)**2)*v
k = (np.dot(u,v)/np.linalg.norm(v)**2)
print(f"k = ", k)
res2 = (np.dot(u,v)/np.linalg.norm(u)**2)*u
print(f"v_p", res)
print(res2)

x = u - res
print(f"v_c", x) 

w = np.linalg.norm(res)
print(w)

k =  -8.2
v_p [-0.   -4.92 -6.56]
[-0.21025641  0.73589744  0.52564103]
v_c [ 2.   -2.08  1.56]
8.2


In [ ]:
import numpy as np
import math

u = np.array([-5, 1, 0])
v = np.array([-5, 3, 1])

norm_n = np.linalg.norm(u)#magni 
norm_v = np.linalg.norm(v)

u_dot_v = np.dot(u, v)

theta_r = math.acos(u_dot_v /(norm_n * norm_v))

theta_d = theta_r * 180 / math.pi


print(theta_r)
print(theta_d)

0.3812749878837846
21.845447639642455
