Reading: Chapter 5 pages 61-72.

Lecture Topics:
1. Matrices
2. Matrix Algebra
3. Matrix Algebra Application: Markov Processes

### I. Matrix Basics

A *matrix* is the result of combining similar row or column vectors into a single mathematical object.

A *tensor* is an algebraic object that describes a multilinear relationship between sets of algebraic objects related to a vector space.

For computational purposes we can consider a matrix to be a 2-dimensional (python "dimension," not math) tensor.

This is an *M* by *N* general matrix:

\begin{align} A = \begin{bmatrix}
    a_{11} & a_{12} & \dots \\
    \vdots & \ddots & \\
    a_{M1} &        & a_{MN}
    \end{bmatrix}
\end{align}

**Examples**.

In [ ]:
A = [[1,2,3], [4,5,6], [7,8,9]]
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
import numpy as np

B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
C = np.arange(1,10)
type(C)
print(C)
#C.shape
#C.reshape(3,3)
#C.reshape(1,9)

In [ ]:
D = np.arange(40).reshape(10,4)
print(D)
D_sub = D[1:8:2,0:3:2] # 0 grab 3
print(D_sub)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[[ 4  6]
 [12 14]
 [20 22]
 [28 30]]


### II. Matrix Algebra

a) Matrix Addition/Subtraction

b) Scalar and Hadamard $\odot$ Multiplication

c) "Standard" Multiplication

d) Matrix Powers

**Examples**.

In [ ]:
A = np.array([[2,2,3],[1,4,5],[9,3,2]])
B = np.array([[-1,-3,9],[2,-6,2],[9,8,7]])
C = np.array([[7,6],[8,-1],[9,2]])
I3 = np.eye(len(A))
Ones = np.ones((3,3))
Zeros = np.zeros((3,3))
v = np.array([[1],[-2],[3]])
u = np.array([[1,-2,3]])
l = 2

**Question**. Is $A^2$ possible if $A$ is a a "tall" matrix? (This is going to be a big deal when we study supervised learning! What do we know about the typical shape of a data matrix?) What must be true of a matrix's dimensions in order for $A^2$ to be well-defined?

**Exercise**. Write a function ```matrix_pow``` that returns the nth power of a given matrix. Check your work using the ```matrix_power``` module form the ```numpy.linalg``` library.

In [ ]:
import numpy as np

def matrix_pow(a, n):
  if n < 1 or n%2 not in {0, 1}:
    raise Exception("n is not a positive interger")
  else:
    ans = a
    for i in range(0,n):
     ans *= a
  return ans


b = np.array([[1,2],[2,3]])
#b = np.array([[1,0,0],[0,1,0],[0,0,1]])
c = b@b
print(c)
print(matrix_pow(b, 3))

#[1 16] [16 81]
#c = a * a * a
#print(c)
#[1 8] [8 27]



[[ 5  8]
 [ 8 13]]
[[   1  256]
 [ 256 6561]]


In [ ]:
import numpy as np
def matrix_pow(A,n):
  if n<1 or n%2 not in {0,1}:
    raise Exception("n is not a positive integer")
  if n == 1:
    return A
  else:
    B = A
    for i in range(0, n - 1):
      B = A@B
    return B


C = 2*np.eye(3)
print(C)

I_3 = matrix_pow(C,2)
print(I_3)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


### III. Linear Dynamical Systems

Suppose that a vector $x_t = <u_1, u_2, ... u_n>$ gives the "state" of the system at time $t$. Linear Dynamical Systems (often called "Markov Processes") follow an *update equation*: $x_{t+1} = Ax_t$ for $t = 0, 1, 2, ...$

Can use either matrix algebra or simulation to find the state of the system at time $t$ in the future.

**Example**. Suppose you know the initial state $x_0$. Write an equation that gives the state of the system at $t = 2$.

**Example**. Suppose you know the initial state $x_0$. Write an equation that gives the state of the system at $t = k$.

**Example**. Epidemic Dynamics: simple model of disease evolution in a population.

State vector at time $t$ is $x_t = <u_1, u_2, u_3, u_4>$, where:

* $u_1$ is the percentage of the population that is susceptible

* $u_2$ is the percentage of the population that is infected

* $u_3$ is the percentage of the population that is recovered/immune

* $u_4$ is the percentage of the population that is deceased.

How the disease evolves from $t$ to $t+1$ (dynamics):

* 5% of susceptible get disease, 95% remain susceptible

* of those infected: 1% die, 10% recover/immune, 4% recover/susceptible, rest remain infected.

Note: the above info is enough to infer that at any time $t$, $\sum_{i=1}^4 u_i =$__?

Model: Use above information to construct "transition" matrix $A$.

**Questions**.
1. What percentage of the population is susceptible at $t = 20$?
2. What percentage of the population is infected at $t = 20$?
3. What percentage of the population is alive at $t = 100$?
4. What is $\lim_{t\to\infty} x_t$? Does this make sense?
5. With some diseases, such as COVID, it is possible to lose ones' immunity. How could this be incorporated into the model? (See Lab 3!)
6. This model is very simple and completely deterministic. How could we modify it to reflect more realistic dynamics?

In [ ]:
import numpy as np
import math
def matrix_pow(A,n):
  if n<1 or n%2 not in {0,1}:
    raise Exception("n is not a positive integer")
  if n == 1:
    return A
  else:
    B = A
    for i in range(0, n - 1):
      B = A@B
    return B

x_0 = np.array([[1],[0],[0],[0]])
print(x_0)
print()
a = np.array([[0.95, 0.04, 0, 0],[0.05, 0.85, 0, 0],[0, 0.1, 1, 0],[0, 0.01, 0, 1]])
print(a)
print()
a_20 = matrix_pow(a, 20)
print(a_20)
print()
x_20 = matrix_pow(a,pow(2,31)-1)@x_0
#x_20 = x_0@a_20

print(x_20)



[[1]
 [0]
 [0]
 [0]]

[[0.95 0.04 0.   0.  ]
 [0.05 0.85 0.   0.  ]
 [0.   0.1  1.   0.  ]
 [0.   0.01 0.   1.  ]]

[[0.45009554 0.14494804 0.         0.        ]
 [0.18118505 0.08772545 0.         0.        ]
 [0.33519946 0.69756956 1.         0.        ]
 [0.03351995 0.06975696 0.         1.        ]]

[[4.44659081e-323]
 [1.48219694e-323]
 [9.09090909e-001]
 [9.09090909e-002]]


In [ ]:
#Q10
import numpy as np

a = np.array([[6, 9, -8, 2],[-5, -4, -1, 0]])
#print(a)

b = np.array([[8, 2, 1],[-5, -3, 3],[-1, 9, 5],[6, 4, -7]])
#print(b)

c = np.dot(a,b)

print(c)

[[ 23 -79 -21]
 [-19  -7 -22]]


In [ ]:
#q11
import numpy as np


def symmetrize(a):
    """
    Return a symmetrized version of NumPy array a.

    Values 0 are replaced by the array value at the symmetric
    position (with respect to the diagonal), i.e. if a_ij = 0,
    then the returned array a' is such that a'_ij = a_ji.

    Diagonal values are left untouched.

    a -- square NumPy array, such that a_ij = 0 or a_ji = 0,
    for i != j.
    """
    return a + a.T - np.diag(a.diagonal())


a = np.array([[-6,-3,1],[9,4,-2],[3,5,-8]])

c = np.array([[-12,6,2],[6, 8, 3], [2,3,-16]])



b = c - a
print(b)

d = b.T
e = a + a.T - np.diag(a.diagonal())
print()
print(d)
print(e)

[[-6  9  1]
 [-3  4  5]
 [-1 -2 -8]]

[[-6 -3 -1]
 [ 9  4 -2]
 [ 1  5 -8]]
[[-6  6  4]
 [ 6  4  3]
 [ 4  3 -8]]


In [ ]:
import numpy as np
c = np.array([[0,-5, 3],[8,9,10],[-2,-8,5]])

print(c + c.T)




[[ 0  3  1]
 [ 3 18  2]
 [ 1  2 10]]


In [ ]:
#q12
import numpy as np
a = np.array([[-8, 5, -5, 0], [8,1,-10,-1],[-3,-7,10,-6],[9,2,6,-2],[7,3,-9,4]])

b= np.array([[6,-6,-2,7],[-3,-5,5,-10],[-9,9,-7,-4],[-1,2,-8,1],[8,3,0,4]])


c = 2 * a - 4 * b
print(c)

[[-40  34  -2 -28]
 [ 28  22 -40  38]
 [ 30 -50  48   4]
 [ 22  -4  44  -8]
 [-18  -6 -18  -8]]


In [ ]:
#q13
import numpy as np
a= np.array([[-9, 6, -4, 2],[5,-5,1,-8],[3,4,-1,8],[-7,-10,-3,-2]])
b = np.array([[4,-2],[-5,-4],[7,2],[-6,5]])

c = np.dot(a,b)
print(c)

[[-106   -4]
 [ 100  -28]
 [ -63   16]
 [  13   38]]


In [ ]:
#Q15
import numpy as np
a = np.array([[-1,5,5],[-4,-3,5]])
print(a)
b = np.array([[4, -3, -1, -1], [2,3,4,-2],[-3,-3,0,1]])
print(b)

c = np.dot(a,b)
#c = a * b
print(c)

[[-1  5  5]
 [-4 -3  5]]
[[ 4 -3 -1 -1]
 [ 2  3  4 -2]
 [-3 -3  0  1]]
[[ -9   3  21  -4]
 [-37 -12  -8  15]]


In [ ]:
#Q16
import numpy as np

a = np.array([[-7,8,5,-6],[6,-5,4,-5],[-9,-3,-5,5]])

b = np.array([[-2,-2,-2,1],[-3,-4,1,3],[-5,6,9,-7]])

c = 2 * a + 6 * b

print(c)

[[-26   4  -2  -6]
 [ -6 -34  14   8]
 [-48  30  44 -32]]


In [ ]:
#q14

import numpy as np



def symmetrize(a):
    """
    Return a symmetrized version of NumPy array a.

    Values 0 are replaced by the array value at the symmetric
    position (with respect to the diagonal), i.e. if a_ij = 0,
    then the returned array a' is such that a'_ij = a_ji.

    Diagonal values are left untouched.

    a -- square NumPy array, such that a_ij = 0 or a_ji = 0,
    for i != j.
    """
    return a + a.T - np.diag(a.diagonal())

a = np.array([[2,3],[6,-6],[9,-1]])

f = np.array([[10,-8],[2,-4]])
#f_t = symmetrize(f)
print(f.T)

c = np.dot(a, f.T)
print(c)


[[10  2]
 [-8 -4]]
[[ -4  -8]
 [108  36]
 [ 98  22]]


In [ ]:
#q20
import numpy as np
a = np.array([[-1,-1],[-1,1],[1,1]])
b = np.array([[1],[-1]])
c = np.dot(a,b)
print(c)


[[ 0]
 [-2]
 [ 0]]


In [ ]:
#q21
import numpy as np
a = np.array([[1,1,5],[-3,-5,4]])
b = np.array([[5],[8],[-1]])
c = np.dot(a,b)
print(c)

[[  8]
 [-59]]


In [ ]:
#q24
import numpy as np
a = np.array([[-1,2],[-2,2],[2,-3]])
b = np.array([[3,5,-3],[0,4,5]])

#ab_t =

[[ -3  -7   9]
 [ 12  16 -13]]


In [ ]:
import numpy as np

a = np.array([[3,-2,4],[1,-5,-8]])

b = a.T
print(b)

[[ 3  1]
 [-2 -5]
 [ 4 -8]]


In [ ]:
#Q27
import numpy as np

a = np.array([[3,4],[5,6],[-1,2]])
print(a)
b = a.T
print()
print(b)

c = np.dot(b, a)
print()
print(c)


[[ 3  4]
 [ 5  6]
 [-1  2]]

[[ 3  5 -1]
 [ 4  6  2]]

[[35 40]
 [40 56]]


In [ ]:
#Q28

import numpy as np

a = np.array([[5,4,-8],[-9,8,-4],[-5,-10,1]])
b = np.array([[1,0,0],[0,1,0],[0,0,1]])

print(np.dot(a,b))

[[  5   4  -8]
 [ -9   8  -4]
 [ -5 -10   1]]


In [ ]:
#Q29
import numpy as np

a = np.array([[3],[-2],[3]])
print(a)
b = np.array([[-2],[1],[-5]])
print(b)

c = 9 * a + 8 * b
print(c)

[[ 3]
 [-2]
 [ 3]]
[[-2]
 [ 1]
 [-5]]
[[ 11]
 [-10]
 [-13]]


In [ ]:
#Q23
import numpy as np
import scipy
a = np.array([[1,4],[-2,8]])

b = np.dot(a,a)



#[a b] dot [w x]
#[c d] dot [y z]

#[x 4] dot [x 4]
#[-2 y] dot [-2 y]

#= [aw + by    ax + bz]
  #[cw + dy    cx + dz]

#[x * x + 4 * -2    x * 4 + 4 * y]
#[]



#[1,4]
#[-2,8]

print(b)

[[ -7  36]
 [-18  56]]


In [ ]:
import numpy as np

a = np.array([[1,0,0],[-1,1,2],[0,0,1]])
b = np.array([[5,0,0],[0,5,0],[0,0,5]])
c = np.array([[5,4,3],[1,8,5],[-2,2,1]])
d = np.array([[0,2,1,-1],[1,0,0,0],[1,3,-1,-1],[0,0,1,0]])
e = np.array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,2,0],[0,0,0,0,1]])

print(np.linalg. inv(e))


[[1.  0.  0.  0.  0. ]
 [0.  1.  0.  0.  0. ]
 [0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  1. ]]
