Reading: pages 84-104  

### I. Matrix Spaces

A <u>matrix equation</u> $A\vec{x} = \vec{b}$ has three possible outcomes for its solution vector $\vec{x}$:

1. There is a unique solution. //their only one solution.
2. There are infinitely many solutions. ..
3. There are no solutions.

**Question**. What does it mean for the matrix equation $Ax=b$ to be "well-defined?"  //

**Question**. What does it mean to "find a solution" to $Ax=b$? (Think in terms of linear combinations of the columns of $A$.)

To do advanced analysis (such as finding eigenvectors or supervised learning models) we need to describe these 3 cases in terms of vector subspaces (the textbook calls them matrix spaces).

Recall that we can build new vectors from old vectors by the vector equation:

\begin{align} \mathbb{w} = \lambda_1\mathbb{v_1} + \lambda_2\mathbb{v_2} + ... + \lambda_n\mathbb{v_p}. \end{align}
These are linear combinations of vectors giving us a (possibly) new vector $w$.

Take $w = \vec{0}$. If there does not exist a set of weights that satisfy the above equation then we say that the set of vectors $V$ is a *linearly independent* set.

Also, recall that a *subspace* of $\mathbb{R}^n$ is a subset $V$ such that:
1. $\vec{0} \in V$
2. $\vec{u}, \vec{v} \in V ⇒ \vec{u} + \vec{v} \in V$
3. $\vec{v} \in V ⇒ k\vec{v} \in V$.

"Matrix Spaces" are special vector subspaces that are generated by matrices (in the context of matrix equations $A\vec{x} = \vec{b}$).

#### Column Space.

If we consider the columns of a matrix to be individual vectors $\vec{a_1}$, $\vec{a_2}$, ..., $\vec{a_m}$, then we can define the *column space* of a matrix $A$ as

$\begin{align}
C(A) & = \{\lambda_1\vec{a_1} + \lambda_2\vec{a_2} + ... + \lambda_m\vec{a_m} : \lambda_i \in \mathbb{R}\}
\end{align}$.

"For a given vector $\vec{v}$, do there exist weights $\lambda_1, ..., \lambda_m$ such that I can get $\vec{v}$ via linear combinations of the columns of matrix $A$?" If yes, then $\vec{v}$ is in the column space of $A$.

**Question**. If $A$ is $n \times m$ then the vectors in $C(A)$ are in $\mathbb{R}^?$.

If $A$ is an $n \times m$ matrix, then the vectors in $C(A)$ (the column space of $A$) are in $\mathbb{R}^n$.

To see why this is the case, recall that the column space of a matrix $A$ is the set of all possible linear combinations of the columns of $A$. The columns of $A$ are $n$-dimensional vectors, since $A$ has $n$ rows. When we take linear combinations of these columns, we are still working with $n$-dimensional vectors. Therefore, the vectors in $C(A)$ are also $n$-dimensional vectors, and they live in $\mathbb{R}^n$.

**Examples**. Describe the column space for each of the following matrices.


1.   [[1, 2], [2, 4]]
2.   [[1, 2], [3, -2]]
3.   [[1, 0, 2], [0, 1, 5], [1, 1, 7]]
4.   [[1, 0, 2], [0, 1, 5], [0, 0, 1]]

**Question**. How can we think of the existence of a solution to the matrix equation $Ax=b$ in terms of $C(A)$? If a solution exists then $b \in$ ____.

**Question**. How can we think of the uniqueness of a solution to $Ax=b$ in terms of $C(A)$?

#### Row space.

$R(A) = C(A^T)$. This does come up but not often in this course.

#### Null Space.

Suppose that $A$ is *n* x *m*. The *null space* $A$ is $N(A) = \{\vec{x} \in \mathbb{R}^m:A\vec{x}=0\}$.

**Question**. What can we conclude about the columns of $A$ if $N(A) = \vec{0}$?

**Question**. If a solution to $Ax = b$ exists, and $N(A) = \vec{0}$ this tells us that the columns of $A$ are ________ __________, which implies that the solution is ______, whereas if a solution to $Ax=b$ exists and $N(A)$ contains more than the $\vec{0}$ then this implies that the solution to $Ax=b$ is not ______.

For any square matrix $A$, if $N(A) = \vec{0}$ we say that matrix $A$ is "non-singular". That is, if $A$ is "singular" then we know that the columns of $A$ are _________ _________.

### I. Matrix Rank

For any matrix A:

$rank(A) =$

*   $r$ (not to be confused with the Person Correlation Coefficient!)
*   number of linearly independent columns
*   dimensionality of the column space
*   number of columns containing "information"

**Example**. Determine the rank of the following data matrix.

In [ ]:
import numpy as np
import pandas as pd

X = np.array([[1, 1, 2], [1,0, 1], [0, 2, 2], [2, 4, 6], [3, 5, 8]])
X = pd.DataFrame(X,columns = ['Var_A','Var_B', 'Var_C'])
X.head()

a = np.linalg.matrix_rank(X)
print(a)

2


### II. Matrix Determinant

The matrix determinant:

a) is only defined for square matrices.

b) summarizes something like the relative size and stability of the matrix. Think of stability as sensitivity of the matrix to overflow/underflow (rounding error) when using it for computation in Python. In general, the closer to zero the determinant is, the less stable the matrix.

c) is exactly zero if $rank(A) < M = N$.

Thus, $det(A) = 0$ means that matrix $A$ is singular.

\**Question**. What does $det(A) = 0$ tell you about whether or not the columns of A are linearly independent?

**Examples**. Find the determinant of the following matrices.

In [ ]:
import numpy as np

A = np.array([[1,2],[2,4]])
B = np.array([[1,2],[2,10]])
A1 = np.array([[1,2],[2,4.0001]]) # Predict the determinant without doing this calculation! How do the stability of A and A1 compare? Demonstrate with np.linalg.solve(A,b)
C = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Hint: What is C[:,0] -2*C[:,1] + C[:,2]?


b = np.array([[1],[1]])
#x =  1* 4.001 - 2 * 2
#print(x)
#A1_rank = np.linalg.matrix_rank(A1)
#print(A1_rank)

#print(np.linalg.det(C))
#print(np.linalg.matrix_rank(C))

x = np.linalg.solve(A1,b)
print(x)

print(np.linalg.det(A1))

a1 = np.array([[1,-5],[-4,8]])
b1 = np.array([[19],[-28]])
print(np.linalg.solve(a1,b1))



[[ 20001.00000005]
 [-10000.00000002]]
9.999999999976704e-05
[[-1.]
 [-4.]]


In [ ]:
import numpy as np

A = np.array([[1,4,6],[2,8,12]])
print(A)

A_rank = np.linalg.matrix_rank(A)
print(A_rank)

a_T = A.T

print(a_T)

a_TT = a_T.T
print(a_T)



B = np.array([[1,4,6],[1,4,6]])
print(B.T)

[[ 1  4  6]
 [ 2  8 12]]
1
[[ 1  2]
 [ 4  8]
 [ 6 12]]
[[ 1  2]
 [ 4  8]
 [ 6 12]]
[[1 1]
 [4 4]
 [6 6]]
