In [1]:
# Import the titanic_train dataset
from google.colab import files

uploaded = files.upload()

Saving trees.csv to trees.csv


In [3]:
# View dataset
import pandas as pd

t = pd.read_csv("trees.csv")
t.head()

Old_Growth  Circumference  Height  Volume
0           0            8.3      70    10.3
1           0            8.6      65    10.3
2           0            8.8      63    10.2
3           1           10.5      72    16.4
4           0           10.7      81    18.8

In [4]:
x = len(t)
print(x)

31


In [13]:
from sklearn import preprocessing
X = t.to_numpy()[:,[0,1,2]]

y = t.to_numpy()[:,3]
print(y)
d = t.to_numpy()[:,[0,1,2,3]]

[10.3 10.3 10.2 16.4 18.8 19.7 15.6 18.2 22.6 19.9 24.2 21.  21.4 21.3
 19.1 22.2 33.8 27.4 25.7 24.9 34.5 31.7 36.3 38.3 42.6 55.4 55.7 58.3
 51.5 51.  77. ]


In [11]:
from sklearn.linear_model import LinearRegression

t_model = LinearRegression().fit(X, y)

print(t_model.coef_)
print()
print(t_model.intercept_)


[2.26009738 4.5671254  0.28996384]

-53.68564400028282


In [17]:
from sklearn import preprocessing
X = t.to_numpy()[:,[1,2,3]]

y = t.to_numpy()[:,0]
print(y)

[0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1.
 1. 1. 1. 1. 1. 1. 1.]


In [21]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler() #construct the scalar object
X_std = scaler.fit_transform(X) #deploy and calculate 
rows, columns = X_std.shape
print(rows)
print(columns)

print(X_std)

31
3
[[-1.60291968 -0.9572127  -1.22883711]
 [-1.50574137 -1.75488995 -1.22883711]
 [-1.44095583 -2.07396086 -1.23502119]
 [-0.89027873 -0.6381418  -0.85160806]
 [-0.82549319  0.79767725 -0.70319007]
 [-0.79310042  1.11674815 -0.64753332]
 [-0.72831488 -1.5953545  -0.90108072]
 [-0.72831488 -0.15953545 -0.74029457]
 [-0.69592211  0.6381418  -0.46819492]
 [-0.66352933 -0.15953545 -0.63516516]
 [-0.63113656  0.47860635 -0.36924959]
 [-0.59874379  0.         -0.56714024]
 [-0.59874379  0.         -0.54240391]
 [-0.50156548 -1.11674815 -0.548588  ]
 [-0.40438717 -0.15953545 -0.68463782]
 [-0.11285223 -0.3190709  -0.49293125]
 [-0.11285223  1.43581905  0.22442236]
 [ 0.01671885  1.5953545  -0.17135894]
 [ 0.14628993 -0.79767725 -0.27648835]
 [ 0.1786827  -1.9144254  -0.32596101]
 [ 0.24346824  0.3190709   0.26771094]
 [ 0.30825379  0.6381418   0.09455662]
 [ 0.4054321  -0.3190709   0.37902443]
 [ 0.89132366 -0.6381418   0.50270609]
 [ 0.98850197  0.15953545  0.76862165]
 [ 1.31242968  0.797

In [22]:
from sklearn.linear_model import LogisticRegression

t_model = LogisticRegression().fit(X_std, y)

print(t_model.coef_)
print()
print(t_model.intercept_)

[[0.36046081 0.52256007 1.14903031]]

[0.65161349]


In [23]:
from sklearn import metrics

y_hat = t_model.predict(X_std)
confusion_matrix = metrics.confusion_matrix(y,y_hat, labels = t_model.classes_)

print(confusion_matrix)

[[11  2]
 [ 4 14]]


In [24]:
tn, fp, fn, tp = confusion_matrix.ravel()
accuracy = (tp + tn)/X.shape[0]
print(accuracy)
#0.8114

0.8064516129032258


In [25]:
precision = tp/(tp+fp)
recall = tp/(tp + fn)

f_1 = 2*precision*recall/(precision + recall)
print(f_1)

#0.7423

0.823529411764706
