In [ ]:
print("Hello World")
print("This is BIS 231 A Wi 23: Linear Algebra with Application")
ak = [1,2,3]



Hello World
This is BIS 231 A Wi 23: Linear Algebra with Application


In [ ]:
import numpy as np

A = np.array([[1,2],[3,6]])
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(np.linalg.matrix_rank(B))



X = np.array([[1,2],[3,-6]])

p = X.dot(X)
print(p)

3
[[  7 -10]
 [-15  42]]


In [5]:
import numpy as np

#A = np.array([[1,1,1],[2,1,0],[-2,-1,0],[1,0,1]])
#B = np.array([[2],[5],[4],[1]])
A = np.array([[1,1,1],[2,1,0],[-2,-1,0],[1,0,1]])
B = np.array([[2],[-2],[4],[-4]])
A_T_A = A.T@A
print(A_T_A)
print()
A_in = np.linalg.inv(A_T_A)
print(A_in)
print()
x = A_in@A.T@B

print(x)

print()
axb = A@x-B
print(axb)

print(np.linalg.norm(axb))

[[10  5  2]
 [ 5  3  1]
 [ 2  1  2]]

[[ 0.625 -1.    -0.125]
 [-1.     2.     0.   ]
 [-0.125  0.     0.625]]

[[-4.5]
 [ 6. ]
 [ 0.5]]

[[ 0.]
 [-1.]
 [-1.]
 [ 0.]]
1.4142135623730951


In [9]:
import numpy as np
A = np.array([[3, 2],[2,3],[-2,4]])
B = np.array([[5],[6],[1]])
A_T_A = A.T@A
print(A_T_A)
print()
#A_in = np.linalg.inv(A_T_A)
print(A.T@B)
print()
print(A_in)
print()
x = A_in@A.T@B

[[17  4]
 [ 4 29]]

[[25]
 [32]]

[[ 0.06079665 -0.00838574]
 [-0.00838574  0.03563941]]

