In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression


X = np.array([[1,2,3],[1,2,5],[1,3,1],[1,8,4],[1,10,1]])
print(X)
#y = np.array([25,30,20,10,32])
y = np.array([[25],[30],[20],[10],[32]])

model = LinearRegression().fit(X, y)


print(model.coef_)
print()
print(model.intercept_)
print()

p = 28.86882668 + 6 * (-0.45202894) + (-1.14595785) * 3
print(p)

[[ 1  2  3]
 [ 1  2  5]
 [ 1  3  1]
 [ 1  8  4]
 [ 1 10  1]]
[[ 0.         -0.45202894 -1.14595785]]

[28.86882668]

22.718779490000003


In [1]:
import numpy as np

x = np.array([[0,4.66,5.21,14.,19.23,1],[4.66,0,9.61,14.18,20.85,1],[5.21,9.61,0,13.59,16.32,1],[14.18,14.18,13.59,0,8.41,1],[19.23,20.85,16.32,8.41,0,1],[1,1,1,1,1,0]])
print(x)

x_i = np.linalg.inv(x)
print(x_i)

y = np.array([[9.33],[10.421],[8.41],[5.22],[10.421],[1]])

x_y = np.dot(x,y)
print(x_y)

[[ 0.    4.66  5.21 14.   19.23  1.  ]
 [ 4.66  0.    9.61 14.18 20.85  1.  ]
 [ 5.21  9.61  0.   13.59 16.32  1.  ]
 [14.18 14.18 13.59  0.    8.41  1.  ]
 [19.23 20.85 16.32  8.41  0.    1.  ]
 [ 1.    1.    1.    1.    1.    0.  ]]
[[-1.98316416e-01  1.04030911e-01  9.48971367e-02  4.70247709e-03
  -5.31410940e-03  5.63110697e-02]
 [ 1.05005961e-01 -1.17753532e-01 -6.65260396e-03  2.48247309e-02
  -5.42455515e-03  3.35691038e-01]
 [ 9.51547724e-02 -6.32117755e-03 -1.15442696e-01  4.96099263e-03
   2.16481086e-02  1.44273130e-01]
 [ 1.53536901e-03  2.65092223e-02  6.48260652e-03 -8.87584865e-02
   5.42312886e-02  5.84203017e-02]
 [-3.37968618e-03 -6.46542374e-03  2.07155568e-02  5.42702858e-02
  -6.51407326e-02  4.05304460e-01]
 [ 5.84120590e-02  3.34865782e-01  1.43340932e-01  5.74711968e-02
   4.05910029e-01 -1.09278722e+01]]
[[366.85379]
 [416.59535]
 [390.76563]
 [483.00169]
 [578.84515]
 [ 43.802  ]]
